<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.11.0" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.16" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../AdventuresSuite.Authorization/AdventuresSuite.Authorization.csproj" />
    <ProjectReference Include="../AdventuresSuite.Companion.Application/AdventuresSuite.Companion.Application.csproj" />
    <ProjectReference Include="../AdventuresSuite.Companion.Contracts/AdventuresSuite.Companion.Contracts.csproj" />
    <ProjectReference Include="../AdventuresSuite.Companion.SqlServer/AdventuresSuite.Companion.SqlServer.csproj" />
    <ProjectReference Include="../AdventuresSuite.Identity/AdventuresSuite.Identity.csproj" />
  </ItemGroup>
</Project>
