import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import {
  collectFinalResidue, collectInventory, deterministicAssignmentId, executeCleanup,
  expectedCleanupScopes, validateAssignmentPlan, validateCatalog, validateInventory
} from './foundation-authority-policy.mjs';

const catalog=JSON.parse(readFileSync(new URL('./foundation-resource-catalog.json',import.meta.url)));
const catalogSha=createHash('sha256').update(readFileSync(new URL('./foundation-resource-catalog.json',import.meta.url))).digest('hex');
const principal='11111111-2222-4333-8444-555555555555';
const roleId=`/subscriptions/${catalog.subscriptionId}/providers/Microsoft.Authorization/roleDefinitions/927117fa-ab5d-42a2-b39e-762663171fa4`;
const inventory=(present=[])=>({schemaVersion:1,operationId:'broker-foundation-inventory-0123456789abcdef',sourceSha:'a'.repeat(40),catalogSha256:catalogSha,entries:catalog.resources.map(x=>({id:x.id,type:x.type,state:present.includes(x.id)?'VerifiedPresent':'VerifiedAbsent'})),result:'Verified'});
const plan=value=>{const scopes=expectedCleanupScopes(catalog,value);return {schemaVersion:1,operationId:'broker-foundation-assign-cleanup-0123456789abcdef',catalogSha256:catalogSha,inventorySha256:'b'.repeat(64),cleanupPrincipalId:principal,cleanupRoleDefinitionId:roleId,assignments:scopes.map(scope=>({scope,principalId:principal,roleDefinitionId:roleId,assignmentId:deterministicAssignmentId(scope,principal)}))};};
const parents=()=>catalog.resources.filter(x=>x.id===x.cleanupParentId).map(x=>x.id);

test('catalog binds the complete exact 23-resource graph and thirteen cleanup parents',()=>{assert.equal(validateCatalog(catalog).resources.length,23);assert.equal(parents().length,13);assert.deepEqual(catalog.resources.map(x=>x.dependencyOrder),Array.from({length:23},(_,i)=>i+1));});
test('empty, early, middle, and complete deployments derive only verified-present cleanup parents',()=>{const cleanupParents=parents();for(const count of [0,1,6,13]){const selected=new Set(cleanupParents.slice(0,count));const present=catalog.resources.filter(x=>selected.has(x.cleanupParentId)).map(x=>x.id);const value=inventory(present);validateInventory(catalog,value);assert.equal(expectedCleanupScopes(catalog,value).length,count);validateAssignmentPlan(catalog,value,plan(value));}});
test('inventory rejects unknown, duplicate, malformed, ambiguous, and wrong-type resources',()=>{const mutations=[v=>v.entries[0].id+='/other',v=>v.entries[1].id=v.entries[0].id,v=>v.entries[0].id='not-an-arm-id',v=>v.entries[0].state='Ambiguous',v=>v.entries[0].type='Microsoft.Network/virtualNetworks'];for(const mutate of mutations){const value=inventory();mutate(value);assert.throws(()=>validateInventory(catalog,value));}});
test('assignment policy rejects broader scopes, absent targets, duplicate, missing, additional, and mismatched bindings',()=>{const value=inventory(parents());const mutations=[p=>p.assignments[0].scope=catalog.resourceGroupId,p=>p.assignments[0].scope=`/subscriptions/${catalog.subscriptionId}`,p=>p.assignments[0].scope=catalog.resources.find(x=>x.id!==x.cleanupParentId).id,p=>p.assignments.push(p.assignments[0]),p=>p.assignments.pop(),p=>p.assignments[0].principalId='22222222-2222-4333-8444-555555555555',p=>p.assignments[0].roleDefinitionId=p.assignments[0].roleDefinitionId.replace('9271','9272'),p=>p.assignments[0].assignmentId=p.assignments[0].assignmentId.replace(/.$/,'0')];for(const mutate of mutations){const candidate=structuredClone(plan(value));mutate(candidate);assert.throws(()=>validateAssignmentPlan(catalog,value,candidate));}});
test('cleanup treats verified absence idempotently and deletes present parents in dependency order',()=>{const value=inventory(parents().slice(0,4));const calls=[];const deleted=new Set();const spawn=(command,args)=>{calls.push(args.join(' '));const id=args[args.indexOf('--ids')+1];if(args[1]==='delete'){deleted.add(id);return {status:0,stdout:'',stderr:''};}if(deleted.has(id))return {status:1,stdout:'',stderr:'(ResourceNotFound)'};const expected=catalog.resources.find(x=>x.id===id);return {status:0,stdout:JSON.stringify({id,type:expected.type}),stderr:''};};const result=executeCleanup(catalog,value,plan(value),spawn,()=>{});assert.equal(result.deletedScopeCount,4);assert.deepEqual(calls.filter(x=>x.includes('resource delete')).map(x=>x.split('--ids ')[1].split(' --')[0]),expectedCleanupScopes(catalog,value));});
test('cleanup fails closed on deletion failure, timeout, and substituted pre-delete evidence',()=>{const value=inventory([parents()[0]]);for(const mode of ['delete','timeout','substitute']){const spawn=(command,args)=>{if(args[1]==='delete')return {status:mode==='delete'?1:0,stdout:'',stderr:''};const id=args[args.indexOf('--ids')+1];return {status:0,stdout:JSON.stringify({id:mode==='substitute'?`${id}/other`:id,type:'Microsoft.Web/sites'}),stderr:''};};assert.throws(()=>executeCleanup(catalog,value,plan(value),spawn,()=>{}),mode==='delete'?/cleanup-delete-failed/:mode==='timeout'?/cleanup-delete-timeout/:/cleanup-predelete-substitution/);}});
test('final residue covers all 23 resources and retains soft-deleted Key Vault without purge',()=>{const value=inventory(parents());const spawn=()=>({status:1,stdout:'',stderr:'(ResourceNotFound)'});const final=collectFinalResidue(catalog,value,'broker-foundation-residue-0123456789abcdef','a'.repeat(40),catalogSha,spawn);assert.equal(final.entries.length,23);assert.equal(final.entries.find(x=>x.type==='Microsoft.KeyVault/vaults').state,'SoftDeletedRetained');assert.equal(final.result,'Clean');validateInventory(catalog,final,{final:true});});
test('complete residue and retained live resources fail final verification',()=>{const value=inventory(parents());const target=catalog.resources[0];const spawn=(command,args)=>{const id=args[args.indexOf('--ids')+1];return id===target.id?{status:0,stdout:JSON.stringify({id,type:target.type}),stderr:''}:{status:1,stdout:'',stderr:'(ResourceNotFound)'};};const final=collectFinalResidue(catalog,value,'broker-foundation-residue-0123456789abcdef','a'.repeat(40),catalogSha,spawn);assert.equal(final.result,'Failure');assert.throws(()=>validateInventory(catalog,final,{final:true}));});
test('inventory collection emits bounded ambiguous evidence rather than raw Azure errors',()=>{const huge=`(AuthorizationFailed)${'secret'.repeat(2000)}`;const result=collectInventory(catalog,'broker-foundation-inventory-0123456789abcdef','a'.repeat(40),catalogSha,()=>({status:1,stdout:'',stderr:huge}));assert.equal(result.result,'Ambiguous');assert.equal(JSON.stringify(result).includes('secret'),false);assert.equal(result.entries.every(x=>x.state==='Ambiguous'),true);});
test('inventory distinguishes bounded process failure without retaining raw evidence',()=>{const result=collectInventory(catalog,'broker-foundation-inventory-0123456789abcdef','a'.repeat(40),catalogSha,()=>({status:null,error:new Error('sensitive')}));assert.equal(result.result,'Failure');assert.equal(JSON.stringify(result).includes('sensitive'),false);assert.equal(result.entries.every(x=>x.state==='Failure'),true);});
