import test from 'node:test'; import assert from 'node:assert/strict';
import { RegistrationBroker, States, transition, validateBinding } from './broker.mjs';
import { GitHubRunnerAdapter } from './github-adapter.mjs';
import { GitHubAppInstallationTokenFactory } from './github-app-adapter.mjs';
import { AtomicOperationStore, ImmutableKeyVaultAppKeyLoader, WorkloadTokenValidator, validateEntraClaims, validateGitHubOidcClaims } from './azure-adapters.mjs';
import { EvidenceMapper, assertEvidence } from './evidence.mjs';
const sha='a'.repeat(40), workflowSha='b'.repeat(40), operationId='operation_1234567890';
function binding(overrides={}) { const approved=new Date(Date.now()-1000); return {repositoryId:1317655952,ownerId:316268438,repository:'adventures-suite/adventures-studio',sourceSha:sha,ref:'refs/heads/main',event:'workflow_dispatch',workflowRef:'adventures-suite/adventures-studio/.github/workflows/private-migration-runner.yml@refs/heads/main',workflowSha,environment:'database-development',operationId,purpose:'private-migration',runnerName:`as-private-migration-${operationId}`,labels:['self-hosted','linux','x64',`operation-${operationId}`,'purpose-private-migration'],runnerGroupId:1,workDirectory:'_work',oidcAudience:'api://future-broker',approvedUtc:approved.toISOString(),deadlineUtc:new Date(approved.getTime()+45*60000).toISOString(),...overrides}; }
class Store { constructor(){this.state=States.Approved;} async compareExchange(_,e,n){if(this.state!==e)return false;this.state=n;return true;} async failIfCurrent(_,e){if(this.state===e)this.state=States.Failed;return true;} }
test('closed transitions and terminal failure',()=>{assert.equal(transition({state:'Approved'},'Issuing').state,'Issuing');assert.throws(()=>transition({state:'Failed'},'Approved'));assert.throws(()=>transition({state:'Issued'},'Approved'));});
test('exact binding accepts only closed values',()=>{assert.equal(validateBinding(binding()).runnerGroupId,1);for(const patch of [{repositoryId:1},{ownerId:1},{sourceSha:'x'},{ref:'refs/heads/dev'},{event:'push'},{environment:'other'},{purpose:'other'},{runnerName:'other'},{labels:['self-hosted']},{runnerGroupId:0},{workDirectory:'tmp'}])assert.throws(()=>validateBinding(binding(patch)));});
test('deadline is exactly 45 minutes and expired fails',()=>{const approved=new Date(Date.now()-46*60000);assert.throws(()=>validateBinding(binding({approvedUtc:approved.toISOString(),deadlineUtc:new Date(approved.getTime()+45*60000).toISOString()})));assert.throws(()=>validateBinding(binding({deadlineUtc:new Date().toISOString()})));});
test('atomic redemption permits one concurrent mint',async()=>{const store=new Store();let calls=0;const github={async generateJitConfiguration(){calls++;await new Promise(r=>setTimeout(r,5));return 'encoded-jit-config-material';}};const broker=new RegistrationBroker(store,github,new EvidenceMapper());const results=await Promise.allSettled([broker.redeem(binding()),broker.redeem(binding())]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.equal(calls,1);});
test('response loss becomes terminal and never mints again',async()=>{const store=new Store();let calls=0;const broker=new RegistrationBroker(store,{async generateJitConfiguration(){calls++;throw new Error('lost');}},new EvidenceMapper());await assert.rejects(broker.redeem(binding()));await assert.rejects(broker.redeem(binding()));assert.equal(calls,1);assert.equal(store.state,'Failed');});
test('cancellation propagates without retry',async()=>{const store=new Store(),controller=new AbortController();controller.abort();let calls=0;const broker=new RegistrationBroker(store,{async generateJitConfiguration(){calls++;}},new EvidenceMapper());await assert.rejects(broker.redeem(binding(),controller.signal),e=>e.name==='AbortError');assert.equal(calls,0);});
test('cleanup deletes at most once and proves zero residue',async()=>{const store=new Store();store.state='Issued';let deletes=0,lists=0;const runner={id:42,name:binding().runnerName,labels:binding().labels.map(name=>({name}))};const github={async listRunners(){return ++lists===1?[runner]:[];},async deleteRunner(id){deletes++;assert.equal(id,42);}};const evidence=await new RegistrationBroker(store,github,new EvidenceMapper()).cleanup(binding());assert.equal(deletes,1);assert.equal(evidence.exactResidueCount,0);assert.equal(store.state,'Closed');});
test('ambiguous cleanup never deletes',async()=>{const store=new Store();store.state='Issued';let deletes=0;const runner={id:42,name:binding().runnerName,labels:binding().labels.map(name=>({name}))};const broker=new RegistrationBroker(store,{async listRunners(){return [runner,{...runner,id:43}]},async deleteRunner(){deletes++;}},new EvidenceMapper());await assert.rejects(broker.cleanup(binding()),/ambiguous/);assert.equal(deletes,0);assert.equal(store.state,'Failed');});
test('runner loss residue fails closed without a second delete',async()=>{const store=new Store();store.state='Issued';let deletes=0;const runner={id:42,name:binding().runnerName,labels:binding().labels.map(name=>({name}))};const broker=new RegistrationBroker(store,{async listRunners(){return [runner]},async deleteRunner(){deletes++;}},new EvidenceMapper());await assert.rejects(broker.cleanup(binding()),/residue/);assert.equal(deletes,1);});
test('GitHub adapter allowlists three endpoint shapes and downscopes token',async()=>{const seen=[];const tokenFactory={async create(scope){assert.deepEqual(scope.repositoryIds,[1317655952]);assert.deepEqual(scope.permissions,{administration:'write'});return {use:callback=>callback('opaque'),dispose(){}};}};const adapter=new GitHubRunnerAdapter({async send(x){seen.push(x);return x.method==='GET'?{runners:[]}:{encoded_jit_config:'abcdefghijklmnop'};}},tokenFactory);await adapter.generateJitConfiguration(binding());await adapter.listRunners();await adapter.deleteRunner(7);assert.equal(seen.length,3);for(const x of seen)assert.equal(x.followRedirects,false);await assert.rejects(adapter.request('POST','/repos/adventures-suite/adventures-studio/issues',{}),/denied/);});
test('GitHub App token factory uses only exact selected repository and permission',async()=>{let request,disposed=0;const factory=new GitHubAppInstallationTokenFactory(12,34,{async use(callback){return callback({});}},{async sign(){return {dispose(){disposed++;}};}},{async send(x){request=x;return {token:'opaque-installation-material',expires_at:new Date(Date.now()+3600000).toISOString()};}});const value=await factory.create({repositoryIds:[1317655952],permissions:{administration:'write'},maximumSeconds:3600});assert.deepEqual(request.body,{repository_ids:[1317655952],permissions:{administration:'write'}});assert.equal(request.followRedirects,false);let observed=false;await value.use(x=>{observed=x.startsWith('opaque')});value.dispose();assert.equal(observed,true);assert.equal(disposed,1);await assert.rejects(factory.create({repositoryIds:[1],permissions:{administration:'write'},maximumSeconds:3600}),/scope/);});
test('runner list bounds fail before use',async()=>{const adapter=new GitHubRunnerAdapter({async send(){return {runners:Array(101)}}},{async create(){return {use:callback=>callback('opaque'),dispose(){}};}});await assert.rejects(adapter.listRunners(),/bounds/);});
test('exact Entra claims reject migration and SQL bootstrap identities',()=>{const expected={iss:'i',aud:'a',tid:'t',oid:'broker-vm',azp:'client',migrationPrincipalId:'migration',sqlBootstrapPrincipalId:'bootstrap'};validateEntraClaims({...expected},expected);assert.throws(()=>validateEntraClaims({...expected,oid:'migration'},expected));assert.throws(()=>validateEntraClaims({...expected,oid:'bootstrap'},expected));});
test('exact GitHub OIDC claims reject substitutions',()=>{const expected={iss:'https://token.actions.githubusercontent.com',aud:'broker',repository_id:'1317655952',repository_owner_id:'316268438',repository:'adventures-suite/adventures-studio',ref:'refs/heads/main',sha,workflow_ref:'wf',event_name:'workflow_dispatch',environment:'database-development'};validateGitHubOidcClaims({...expected},expected);for(const key of Object.keys(expected))assert.throws(()=>validateGitHubOidcClaims({...expected,[key]:'wrong'},expected));});
test('signature verification precedes exact GitHub and Entra claim validation',async()=>{let verifies=0;const github={iss:'https://token.actions.githubusercontent.com',aud:'broker',repository_id:'1317655952',repository_owner_id:'316268438',repository:'adventures-suite/adventures-studio',ref:'refs/heads/main',sha,workflow_ref:'wf',event_name:'workflow_dispatch',environment:'database-development'};const verifier=new WorkloadTokenValidator({async verify(token,policy){verifies++;assert.equal(token,'opaque');assert.deepEqual(policy.algorithms,['RS256']);return github;}});await verifier.validateGitHub('opaque',github);assert.equal(verifies,1);const rejecting=new WorkloadTokenValidator({async verify(){throw new Error('signature');}});await assert.rejects(rejecting.validateGitHub('unsigned',github),/signature/);});
test('operation store writes only closed state fields',async()=>{let request;const store=new AtomicOperationStore({async conditionalUpdate(x){request=x;return true;}});await store.compareExchange(operationId,'Approved','Issuing');assert.deepEqual(request.allowedFields,['state','updatedUtc','failureCode']);assert.equal(JSON.stringify(request).includes('token'),false);});
test('operation arm stores only bounded hashes and bindings',async()=>{let request;const store=new AtomicOperationStore({async conditionalInsert(x){request=x;return true;}});await store.arm({operationId,repositoryId:1317655952,ownerId:316268438,sourceSha:sha,manifestHash:'c'.repeat(64),purpose:'private-migration',runnerNameHash:'d'.repeat(64),labelHash:'e'.repeat(64),deadlineUtc:new Date().toISOString()});assert.equal(request.state,'Approved');assert.equal(JSON.stringify(request).includes('jit'),false);assert.equal(JSON.stringify(request).includes('token'),false);});
test('Key Vault loader requires immutable version and disposes key',async()=>{assert.throws(()=>new ImmutableKeyVaultAppKeyLoader({},'/vault/secrets/name'));let disposed=false;const loader=new ImmutableKeyVaultAppKeyLoader({async getExactVersion(){return {dispose(){disposed=true;}}}},'/subscriptions/s/resourceGroups/r/providers/Microsoft.KeyVault/vaults/v/secrets/k/01234567-89ab-cdef-0123-456789abcdef');await loader.use(async()=>true);assert.equal(disposed,true);});
test('evidence rejects prohibited and unbounded fields',()=>{assert.throws(()=>assertEvidence({installationToken:'x'}));assert.throws(()=>assertEvidence({safe:'x'.repeat(5000)}));assert.doesNotThrow(()=>new EvidenceMapper().closed(binding(),null,0,0));});
