import test from 'node:test';
import assert from 'node:assert/strict';
import { generateKeyPairSync } from 'node:crypto';
import { Readable } from 'node:stream';
import { assertAnonymousDescriptor, assertBoundedEvidence, DestinationContentType, DestinationSecretName, importFictionalOrFutureKey } from './key-custody-importer.mjs';

const vaultId = '/subscriptions/5ace9cdd-06d1-47d9-8214-1e7c756d076a/resourceGroups/rg-adventures-suite-dev/providers/Microsoft.KeyVault/vaults/kv-adventures-runner-dev';
const startedUtc = '2026-08-13T12:00:00.000Z';
const completedUtc = '2026-08-13T12:00:01.000Z';
function fictionalPem() { return generateKeyPairSync('rsa', { modulusLength: 2048, privateKeyEncoding: { format: 'pem', type: 'pkcs8' }, publicKeyEncoding: { format: 'pem', type: 'spki' } }).privateKey; }
function args(overrides={}) { return { input: Readable.from([Buffer.from(fictionalPem())]), operationId:'broker-key-0123456789abcdef', vaultId, githubKeyId:'1234567', startedUtc, now:()=>completedUtc, ...overrides }; }

test('fictional key import emits only bounded immutable metadata', async()=>{let observed;const evidence=await importFictionalOrFutureKey(args({secretClient:{async setSecret(name,value,options){observed={name,value,options};return {id:'https://kv-adventures-runner-dev.vault.azure.net/secrets/github-app-4590229-private-key/0123456789abcdef0123456789abcdef'};}}}));assert.equal(observed.name,DestinationSecretName);assert.equal(observed.options.contentType,DestinationContentType);assert.match(observed.value,/BEGIN PRIVATE/);assertBoundedEvidence(evidence);assert.equal(JSON.stringify(evidence).includes('PRIVATE KEY'),false);assert.match(evidence.publicKeyFingerprint,/^SHA256:/);});
test('versionless or wrong secret readback fails closed',async()=>{for(const id of ['https://kv-adventures-runner-dev.vault.azure.net/secrets/github-app-4590229-private-key','https://kv-adventures-runner-dev.vault.azure.net/secrets/other/0123456789abcdef0123456789abcdef'])await assert.rejects(importFictionalOrFutureKey(args({secretClient:{async setSecret(){return {id};}}})),/immutable-version-readback/);});
test('malformed weak and oversized material fail before import',async()=>{let calls=0;const secretClient={async setSecret(){calls++;}};await assert.rejects(importFictionalOrFutureKey(args({secretClient,input:Readable.from(['not-a-key'])})),/pkcs8-rsa-required/);await assert.rejects(importFictionalOrFutureKey(args({secretClient,input:Readable.from([Buffer.alloc(16385)])})),/pem-size-bound/);assert.equal(calls,0);});
test('cancellation remains distinct and never imports',async()=>{const controller=new AbortController();controller.abort();let calls=0;await assert.rejects(importFictionalOrFutureKey(args({signal:controller.signal,secretClient:{async setSecret(){calls++;}}})),e=>e.name==='AbortError');assert.equal(calls,0);});
test('wrong operation vault key and timestamp bindings fail before import',async()=>{const secretClient={async setSecret(){throw new Error('should-not-run');}};for(const patch of [{operationId:'wrong'},{vaultId:'/wrong'},{githubKeyId:'x'},{startedUtc:'not-time'}])await assert.rejects(importFictionalOrFutureKey(args({secretClient,...patch})));});
test('descriptor gate accepts only inherited anonymous pipe or socket',()=>{assert.doesNotThrow(()=>assertAnonymousDescriptor(3,{isFIFO:()=>true,isSocket:()=>false}));assert.throws(()=>assertAnonymousDescriptor(0,{isFIFO:()=>true,isSocket:()=>false}),/nonpersistent/);assert.throws(()=>assertAnonymousDescriptor(3,{isFIFO:()=>false,isSocket:()=>false}),/nonpersistent/);});
test('failure evidence contains only a stable code',async()=>{const secretClient={async setSecret(){const error=new Error('sensitive response body');error.code='service-failure';throw error;}};await assert.rejects(importFictionalOrFutureKey(args({secretClient})),e=>e.code==='service-failure');});
test('source and aggregate buffers are zeroized after success',async()=>{const source=Buffer.from(fictionalPem());await importFictionalOrFutureKey(args({input:Readable.from([source]),secretClient:{async setSecret(){return {id:'https://kv-adventures-runner-dev.vault.azure.net/secrets/github-app-4590229-private-key/0123456789abcdef0123456789abcdef'};}}}));assert.equal(source.every(byte=>byte===0),true);});
