#!/usr/bin/env bash
set -euo pipefail
root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)"; dir="$root/infrastructure/runner-registration-broker"; workflow="$root/.github/workflows/ephemeral-runner-registration-broker.yml"
require(){ rg -q --fixed-strings -- "$1" "$2"; }; reject(){ ! rg -q --fixed-strings -- "$1" "$2"; }
node --test "$dir/broker.test.mjs"
jq -e '.repository.id==1317655952 and .repository.ownerId==316268438 and .maximumLifetimeMinutes==45 and .workDirectory=="_work" and .githubApp.repositorySelection=="selected" and .githubApp.repositoryPermissions.administration=="write" and .githubApp.organizationPermissions=={} and .githubApp.userPermissions=={} and .githubApp.webhooks==false and (.prohibitedGithubPrincipals|index("migrationUami"))!=null and (.prohibitedGithubPrincipals|index("sqlBootstrapUami"))!=null' "$dir/contracts.json" >/dev/null
jq -e '.additionalProperties==false and .properties.deleteAttempts.maximum==1 and .properties.repositoryId.const==1317655952 and .properties.ownerId.const==316268438' "$dir/evidence.schema.json" >/dev/null
require "generate-jitconfig" "$dir/github-adapter.mjs"; require "followRedirects:false" "$dir/github-adapter.mjs"; require "repositoryIds:[1317655952]" "$dir/github-adapter.mjs"; require "permissions:{administration:'write'}" "$dir/github-adapter.mjs"
require "repository_ids:[1317655952]" "$dir/github-app-adapter.mjs"; require "permissions:{administration:'write'}" "$dir/github-app-adapter.mjs"; require "maximumSeconds!==3600" "$dir/github-app-adapter.mjs"; require "followRedirects:false" "$dir/github-app-adapter.mjs"
reject "registration-token" "$dir/github-adapter.mjs"; reject "api.github.com/orgs" "$dir/github-adapter.mjs"
require "immutable-secret-version-required" "$dir/azure-adapters.mjs"; require "migrationPrincipalId" "$dir/azure-adapters.mjs"; require "sqlBootstrapPrincipalId" "$dir/azure-adapters.mjs"
require "States.Approved,new Set([States.Issuing,States.Failed])" "$dir/broker.mjs"; require "States.Issuing,new Set([States.Issued,States.Failed])" "$dir/broker.mjs"; require "States.Issued,new Set([States.Cleaning,States.Failed])" "$dir/broker.mjs"; require "States.Cleaning,new Set([States.Closed,States.Failed])" "$dir/broker.mjs"; require "45*60*1000" "$dir/broker.mjs"
require "environment: database-development" "$workflow"; require "workflow_dispatch:" "$workflow"; require "if: always()" "$workflow"; require "cancel-in-progress: false" "$workflow"; require "Deliberately stop before Azure login, deployment, arming, or JIT generation" "$workflow"
reject "azure/login@" "$workflow"; reject "az deployment" "$workflow"; reject "generate-jitconfig" "$workflow"; reject "curl " "$workflow"; reject "continue-on-error" "$workflow"
test "$(rg -c '^\s*- uses:' "$workflow")" = 2; test "$(rg -c 'actions/checkout@11d5960a326750d5838078e36cf38b85af677262' "$workflow")" = 2
require "param functionRuntimeVersion string" "$dir/main.bicep"; require "param githubAppKeySecretVersionResourceId string" "$dir/main.bicep"; require "param githubAppId string" "$dir/main.bicep"; require "param githubInstallationId string" "$dir/main.bicep"; require "param runnerGroupId int" "$dir/main.bicep"
require "param brokerIntegrationSubnetResourceId string" "$dir/main.bicep"; require "param privateEndpointSubnetResourceId string" "$dir/main.bicep"; require "param tablePrivateDnsZoneResourceId string" "$dir/main.bicep"
require "name: 'FC1'" "$dir/main.bicep"; require "alwaysOn: false" "$dir/main.bicep"; require "allowSharedKeyAccess: false" "$dir/main.bicep"; require "publicNetworkAccess: 'Disabled'" "$dir/main.bicep"; require "groupIds: ['table']" "$dir/main.bicep"; reject "roleAssignments" "$dir/main.bicep"; reject "publicIPAddress" "$dir/main.bicep"; reject "Microsoft.Sql" "$dir/main.bicep"; reject "default:" "$dir/main.bicep"
for prohibited in jitConfiguration appPrivateKey appJwt installationToken azureToken authorizationHeader rawClaims rawResponses vmBootstrapContent packageUrl connectionString arbitraryLabels; do jq -e --arg p "$prohibited" '.prohibitedMaterial|index($p)!=null' "$dir/contracts.json" >/dev/null; done
echo 'runner registration broker policy tests passed'
